/**
 * Markdown renderers for the reports the CLI writes into `90 Meta/`.
 * These are tool artifacts (excluded from document validation), so they are
 * plain readable markdown rather than typed vault documents.
 */
import { type CompilerResult } from "../core/compiler.js";
import { type CompilerIssue } from "../core/issues.js";
import { type KosTask } from "../tasks/task-model.js";
import { type TaskGraph } from "../planner/planner.js";
import { type ExecutionPlan } from "../scheduler/scheduler.js";

function issueTable(issues: CompilerIssue[]): string {
  if (issues.length === 0) return "_none_\n";
  const header =
    "| Severity | Rule | Message | Path | Line |\n| --- | --- | --- | --- | --- |";
  const rows = issues
    .map(
      (i) =>
        `| ${i.severity} | ${i.ruleId} | ${escapePipes(i.message)} | ${
          i.path ?? ""
        } | ${i.line ?? ""} |`,
    )
    .join("\n");
  return `${header}\n${rows}\n`;
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export function renderValidationReport(
  result: CompilerResult,
  vaultPath: string,
  now: string,
): string {
  return `# Validation Report

_Generated by \`kos validate\` on ${now} for \`${vaultPath}\`._

- Documents scanned: **${result.docCount}**
- Errors: **${result.errors.length}**
- Warnings: **${result.warnings.length}**
- Suggestions: **${result.suggestions.length}**

## Errors

${issueTable(result.errors)}
## Warnings

${issueTable(result.warnings)}
## Suggestions

${issueTable(result.suggestions)}
`;
}

export function renderCompilerReport(
  result: CompilerResult,
  tasks: KosTask[],
  now: string,
): string {
  const a = result.analysis;
  const missing =
    a.missingLayers.length === 0
      ? "_none — every knowledge layer has at least one document_"
      : a.missingLayers.map((l) => `- ${l}`).join("\n");
  const questions =
    a.openQuestions.length === 0
      ? "_none found_"
      : a.openQuestions
          .slice(0, 50)
          .map((q) => `- ${escapePipes(q.text)} _(${q.path})_`)
          .join("\n");
  const open = tasks.filter(
    (t) => t.status === "open" || t.status === "in_progress",
  );
  const recs =
    open.length === 0
      ? "_no open tasks_"
      : open
          .map((t) => `- **[${t.priority}]** ${t.id} — ${t.goal} _(${t.type})_`)
          .join("\n");

  return `# Compiler Report

_Generated by \`kos compile\` on ${now}._

- Knowledge score: **${result.score}/100**
- Documents: **${result.docCount}**, Errors: **${result.errors.length}**, Warnings: **${result.warnings.length}**

## Errors

${issueTable(result.errors)}
## Warnings

${issueTable(result.warnings)}
## Missing knowledge layers

${missing}

## Open questions across the vault

${questions}

## Task recommendations

${recs}
`;
}

export function renderKnowledgeScore(
  result: CompilerResult,
  now: string,
): string {
  const b = result.scoreBreakdown;
  const layerLines = Object.entries(result.analysis.coverage.perLayer)
    .map(([layer, covered]) => `| ${layer} | ${covered ? "✓" : "—"} |`)
    .join("\n");
  return `# Knowledge Score

_Generated by \`kos compile\` on ${now}._

## Overall: ${b.score} / 100

Three independent components, combined deterministically:

\`\`\`
Quality  = clamp(100 - 6*errors - 1.5*warnings, 0, 100)   = ${b.quality}
Coverage = layersCovered / layersTotal                    = ${b.layersCovered}/${b.layersTotal} (${b.coverage}%)
Overall  = round(0.6*Quality + 0.4*Coverage)              = ${b.score}
\`\`\`

- Errors: **${b.errors}**
- Warnings: **${b.warnings}**

## Knowledge-layer coverage

| Layer | Has a real document? |
| --- | --- |
${layerLines}
`;
}

export function renderIngestionReport(args: {
  inputFile: string;
  inboxRel: string;
  taskCount: number;
  now: string;
}): string {
  return `# Ingestion Report

_Generated by \`kos ingest\` on ${args.now}._

- Input ingested: \`${args.inputFile}\`
- Copied to: \`${args.inboxRel}\`
- Seed tasks created: **${args.taskCount}**

## What happened

The input was captured verbatim into \`00 Inbox/\`. No documents were written into
canonical folders — promotion happens later through controlled tasks, not at ingest.

## Next steps

1. Run \`kos compile\` to score the vault and refresh the task queue.
2. Run \`kos run --max-iterations N\` to let the compiler dispatch tasks one at a time.

See \`90 Meta/Task Queue.md\` for the seeded tasks.
`;
}

/** The Planner's view: nodes, their dependencies, and what they block. */
export function renderTaskGraph(graph: TaskGraph, now: string): string {
  const byId = new Map(graph.tasks.map((t) => [t.id, t]));
  const tableRows =
    graph.tasks.length === 0
      ? "| — | — | — | — | — | — |"
      : graph.tasks
          .map(
            (t) =>
              `| ${t.id} | ${t.type} | ${t.priority} | ${t.status} | ${
                t.dependencies.join(", ") || "—"
              } | ${(graph.blocks[t.id] ?? []).join(", ") || "—"} |`,
          )
          .join("\n");

  // Indented dependency tree rooted at tasks with no dependencies. A task with
  // multiple prerequisites appears under each — a readable view, not a strict DAG.
  const treeLines: string[] = [];
  const visit = (id: string, depth: number, seen: Set<string>): void => {
    const t = byId.get(id);
    if (!t || seen.has(id)) return;
    treeLines.push(
      `${"  ".repeat(depth)}- ${t.id} [${t.priority}] ${t.type} (${t.status})`,
    );
    const next = new Set(seen).add(id);
    for (const dependent of graph.blocks[id] ?? []) visit(dependent, depth + 1, next);
  };
  for (const root of graph.tasks.filter((t) => t.dependencies.length === 0)) {
    visit(root.id, 0, new Set());
  }
  const tree = treeLines.join("\n") || "_no tasks_";

  return `# Task Graph

_Generated by \`kos\` on ${now}. The Planner's view of work: nodes are tasks, edges are dependencies._

| ID | Type | Priority | Status | Depends on | Blocks |
| --- | --- | --- | --- | --- | --- |
${tableRows}

## Dependency tree

${tree}
`;
}

/** The Scheduler's view: the order work would run, and what is blocked. */
export function renderExecutionPlan(plan: ExecutionPlan, now: string): string {
  const sequence =
    plan.sequence.length === 0
      ? "_nothing ready to run_"
      : plan.sequence
          .map(
            (t, i) =>
              `${i + 1}. ${t.id} [${t.priority}] ${t.type} — ${escapePipes(t.goal)}`,
          )
          .join("\n");
  const blocked =
    plan.blocked.length === 0
      ? "_none_"
      : plan.blocked
          .map(
            (b) =>
              `- ${b.task.id} ${b.task.type} — waiting on: ${
                b.missing.join(", ") || "(unresolvable dependency)"
              }`,
          )
          .join("\n");

  return `# Execution Plan

_Generated by \`kos\` on ${now}. The Scheduler's view: the order tasks would execute as dependencies clear._

## Sequence

${sequence}

## Blocked

${blocked}
`;
}
