/**
 * Markdown renderers for the reports the CLI writes into `90 Meta/`.
 * These are tool artifacts (excluded from document validation), so they are
 * plain readable markdown rather than typed vault documents.
 */
import { CompilerResult } from "../core/compiler.js";
import { CompilerIssue } from "../core/issues.js";

function issueTable(issues: CompilerIssue[]): string {
  if (issues.length === 0) return "_none_\n";
  const header =
    "| Severity | Rule | Message | Path | Line |\n| --- | --- | --- | --- | --- |";
  const rows = issues
    .map(
      (i) =>
        `| ${i.severity} | ${i.ruleId} | ${escapePipes(i.message)} | ${
          i.path ?? ""
        } | ${i.line ?? ""} |`,
    )
    .join("\n");
  return `${header}\n${rows}\n`;
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export function renderValidationReport(
  result: CompilerResult,
  vaultPath: string,
  now: string,
): string {
  return `# Validation Report

_Generated by \`kos validate\` on ${now} for \`${vaultPath}\`._

- Documents scanned: **${result.docCount}**
- Errors: **${result.errors.length}**
- Warnings: **${result.warnings.length}**
- Suggestions: **${result.suggestions.length}**

## Errors

${issueTable(result.errors)}
## Warnings

${issueTable(result.warnings)}
## Suggestions

${issueTable(result.suggestions)}
`;
}

export function renderCompilerReport(
  result: CompilerResult,
  now: string,
): string {
  const a = result.analysis;
  const missing =
    a.missingLayers.length === 0
      ? "_none — every knowledge layer has at least one document_"
      : a.missingLayers.map((l) => `- ${l}`).join("\n");
  const questions =
    a.openQuestions.length === 0
      ? "_none found_"
      : a.openQuestions
          .slice(0, 50)
          .map((q) => `- ${escapePipes(q.text)} _(${q.path})_`)
          .join("\n");
  const recs =
    result.tasks.length === 0
      ? "_no new task recommendations_"
      : result.tasks
          .map((t) => `- **[${t.priority}]** ${t.goal} _(${t.type})_`)
          .join("\n");

  return `# Compiler Report

_Generated by \`kos compile\` on ${now}._

- Knowledge score: **${result.score}/100**
- Documents: **${result.docCount}**, Errors: **${result.errors.length}**, Warnings: **${result.warnings.length}**

## Errors

${issueTable(result.errors)}
## Warnings

${issueTable(result.warnings)}
## Missing knowledge layers

${missing}

## Open questions across the vault

${questions}

## Task recommendations

${recs}
`;
}

export function renderKnowledgeScore(
  result: CompilerResult,
  now: string,
): string {
  const b = result.scoreBreakdown;
  const layerLines = Object.entries(result.analysis.coverage.perLayer)
    .map(([layer, covered]) => `| ${layer} | ${covered ? "✓" : "—"} |`)
    .join("\n");
  return `# Knowledge Score

_Generated by \`kos compile\` on ${now}._

## Score: ${b.score} / 100

The score is deterministic:

\`\`\`
quality  = clamp(100 - 6*errors - 1.5*warnings, 0, 100)   = ${b.quality}
coverage = layersCovered / layersTotal                    = ${b.layersCovered}/${b.layersTotal} (${b.coverage}%)
score    = round(0.6*quality + 0.4*coverage*100)          = ${b.score}
\`\`\`

- Errors: **${b.errors}**
- Warnings: **${b.warnings}**

## Knowledge-layer coverage

| Layer | Has a real document? |
| --- | --- |
${layerLines}
`;
}

export function renderIngestionReport(args: {
  inputFile: string;
  inboxRel: string;
  taskCount: number;
  now: string;
}): string {
  return `# Ingestion Report

_Generated by \`kos ingest\` on ${args.now}._

- Input ingested: \`${args.inputFile}\`
- Copied to: \`${args.inboxRel}\`
- Seed tasks created: **${args.taskCount}**

## What happened

The input was captured verbatim into \`00 Inbox/\`. No documents were written into
canonical folders — promotion happens later through controlled tasks, not at ingest.

## Next steps

1. Run \`kos compile\` to score the vault and refresh the task queue.
2. Run \`kos run --max-iterations N\` to let the compiler dispatch tasks one at a time.

See \`90 Meta/Task Queue.md\` for the seeded tasks.
`;
}
