/**
 * Markdown renderers for the founder-interview artifacts.
 *
 * `renderInterviewDoc` produces the captured interview saved under
 * `00 Inbox/Interviews/` (a well-formed `meeting` document, though as an Inbox
 * capture it is exempt from validation). The other two render the `90 Meta/`
 * projections: pending founder questions and the chronological interview log.
 * All three are pure functions of their inputs.
 */
import { type KosTask } from "../tasks/task-model.js";

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export interface InterviewDocInput {
  task: KosTask;
  questions: string[];
  answers: string[];
  /** Calendar day (YYYY-MM-DD) used for frontmatter dates. */
  now: string;
}

/** Render the interview capture document (grouped Q&A, one file per interview). */
export function renderInterviewDoc(input: InterviewDocInput): string {
  const { task, questions, answers, now } = input;
  const qaLines = (render: (i: number) => string): string =>
    questions.length === 0
      ? "- _(no questions)_"
      : questions.map((_q, i) => render(i)).join("\n");

  const questionList = qaLines(
    (i) => `- Q${i + 1}: ${(questions[i] ?? "").trim()}`,
  );
  const answerList = qaLines(
    (i) => `- A${i + 1}: ${(answers[i] ?? "(no answer provided)").trim()}`,
  );

  return `---
type: meeting
status: draft
created: ${now}
updated: ${now}
owner: founder
tags: [interview, founder]
parents: []
children: []
related: []
---

# Founder Interview — ${task.id}

Captured founder answers for task ${task.id}: "${task.goal}".

## Purpose

Record the founder's direct input for "${task.goal}". This is human input gathered
through \`kos run\`; no AI answered on the founder's behalf.

## Context

Generated for founder-interview task ${task.id} on ${now}. The questions below were
raised by the planner because they require founder judgement rather than documentation work.

## Question

${questionList}

## Answer

${answerList}

## Relationships

- Source task: ${task.id} (${task.type})

## Open Questions

- Which canonical documents should these answers be promoted into?

## Related Documents

- [[Home]]
`;
}

/** Render the pending founder questions projection from the task store. */
export function renderFounderQuestions(tasks: KosTask[], now: string): string {
  const pending = tasks.filter(
    (t) =>
      t.type === "founder_interview" &&
      (t.status === "open" || t.status === "in_progress"),
  );

  const body =
    pending.length === 0
      ? "_no pending founder questions_"
      : pending
          .map((t) => {
            const qs = t.questions ?? [];
            const items =
              qs.length === 0
                ? "  - _(no questions recorded)_"
                : qs.map((q) => `  - ${escapePipes(q)}`).join("\n");
            return `### ${t.id} [${t.priority}] — ${escapePipes(t.goal)}\n\n${items}`;
          })
          .join("\n\n");

  return `# Founder Questions

_Generated by \`kos\` on ${now}. Pending questions awaiting founder input; answered through \`kos run\`._

${body}

Pending interviews: ${pending.length}
`;
}

export interface InterviewLogEntry {
  fileName: string;
  /** Created date from frontmatter, or "" if unknown. */
  created: string;
  title: string;
}

/** Render the chronological log of saved interview files. */
export function renderInterviewLog(
  entries: InterviewLogEntry[],
  now: string,
): string {
  const sorted = [...entries].sort((a, b) => a.fileName.localeCompare(b.fileName));
  const rows =
    sorted.length === 0
      ? "| — | — | _no interviews recorded_ |"
      : sorted
          .map(
            (e) =>
              `| ${e.created || "—"} | ${escapePipes(e.fileName)} | ${escapePipes(
                e.title,
              )} |`,
          )
          .join("\n");

  return `# Interview Log

_Generated by \`kos\` on ${now}. Founder interviews captured in \`00 Inbox/Interviews/\`._

| Date | File | Title |
| --- | --- | --- |
${rows}

Interviews recorded: ${sorted.length}
`;
}
