/**
 * Markdown renderer for the Promotion Report (`90 Meta/Promotion Report.md`).
 *
 * Pure function over the current proposal documents + task set. As elsewhere in
 * KOS there is no event log: the promotion lifecycle is derived from each
 * proposal's `status` frontmatter (the machine state), exactly like every other
 * `90 Meta/` projection. The report makes the audit legible: what is pending,
 * what was merged, what was rejected, and what changes were requested.
 */
import { type KosTask, isPromotionType } from "../tasks/task-model.js";

/** A lightweight view of one proposal document, derived by the command. */
export interface ProposalSummary {
  id: string;
  title: string;
  status: string;
  /** Target canonical document (wikilink/relPath). */
  target: string;
  /** Vault-relative path of the proposal document. */
  relPath: string;
}

export interface PromotionReportInput {
  proposals: ProposalSummary[];
  tasks: KosTask[];
  /** Canonical documents merged into this run (vault-relative paths). */
  mergedDocs: string[];
  now: string;
}

function proposalLine(p: ProposalSummary): string {
  return `- \`${p.id}\` ${p.title} → ${p.target} (\`${p.relPath}\`)`;
}

function section(heading: string, lines: string[], empty: string): string {
  const body = lines.length > 0 ? lines.join("\n") : `_${empty}_`;
  return `## ${heading}\n\n${body}`;
}

/** Render the full Promotion Report from proposal documents + tasks. */
export function renderPromotionReport(input: PromotionReportInput): string {
  const byStatus = (status: string): ProposalSummary[] =>
    input.proposals.filter((p) => p.status === status);

  const pending = byStatus("review");
  const merged = byStatus("merged");
  const rejected = byStatus("rejected");
  const changes = byStatus("draft");

  const openProposalTasks = input.tasks.filter(
    (t) => isPromotionType(t.type) && (t.status === "open" || t.status === "in_progress"),
  );

  const mergedDocLines = input.mergedDocs.map((d) => `- \`${d}\``);

  const sections = [
    section("Pending proposals", pending.map(proposalLine), "No proposals awaiting review."),
    section(
      "Canonical documents updated",
      mergedDocLines,
      "No canonical documents were updated this run.",
    ),
    section("Merged proposals", merged.map(proposalLine), "No proposals merged yet."),
    section("Rejected proposals", rejected.map(proposalLine), "No proposals rejected."),
    section("Changes requested", changes.map(proposalLine), "No proposals awaiting revision."),
    section(
      "Proposal history",
      input.proposals.map((p) => `- \`${p.id}\` [${p.status}] ${p.title}`),
      "No proposals exist yet.",
    ),
    section(
      "Open proposal tasks",
      openProposalTasks.map((t) => `- \`${t.id}\` [${t.priority}] — ${t.goal}`),
      "No open proposal tasks.",
    ),
  ];

  return `# Promotion Report

_Generated by \`kos promote\` on ${input.now}. **Canonical knowledge is earned, not generated.**
A proposal becomes company truth only when the founder approves it; an approved change is
appended to its target document with provenance, never silently rewritten. The Kernel and
research evidence are immutable. This report derives its state from proposal \`status\` — there
is no separate event log._

Proposals: ${input.proposals.length} (pending ${pending.length}, merged ${merged.length}, rejected ${rejected.length}, changes requested ${changes.length}).

${sections.join("\n\n")}
`;
}
