/**
 * Markdown renderer for the Research Report (`90 Meta/Research Report.md`).
 *
 * Pure function over the current task set + the docs created this run. There is
 * no event log in KOS (by design); research lifecycle is derived from task
 * status, exactly like every other `90 Meta/` projection. The report states up
 * front that research is advisory evidence, never canonical knowledge.
 */
import { type KosTask, isResearchType } from "../tasks/task-model.js";

export interface ResearchReportInput {
  tasks: KosTask[];
  /** Vault-relative paths of research docs created/updated this run. */
  createdDocs: string[];
  now: string;
}

function taskLine(t: KosTask): string {
  return `- \`${t.id}\` [${t.priority}] ${t.type} — ${t.goal}`;
}

function section(heading: string, lines: string[], empty: string): string {
  const body = lines.length > 0 ? lines.join("\n") : `_${empty}_`;
  return `## ${heading}\n\n${body}`;
}

/** Render the full Research Report from the task set and created documents. */
export function renderResearchReport(input: ResearchReportInput): string {
  const research = input.tasks.filter((t) => isResearchType(t.type));
  const completed = research.filter((t) => t.status === "complete");
  const failed = research.filter((t) => t.status === "failed");
  const gaps = research.filter(
    (t) => t.status === "open" || t.status === "blocked" || t.status === "in_progress",
  );
  // Follow-ups the Research Worker proposed that are not themselves research
  // tasks (e.g. founder interviews, ADRs) — open and awaiting other rails.
  const followUps = input.tasks.filter(
    (t) => t.origin === "research" && !isResearchType(t.type) && t.status === "open",
  );

  const docs = input.createdDocs.map((d) => `- \`${d}\``);

  const sections = [
    section("Completed research", completed.map(taskLine), "No completed research tasks yet."),
    section("Research documents created", docs, "No research documents created this run."),
    section("Failed research", failed.map(taskLine), "No failed research tasks."),
    section("Follow-up tasks", followUps.map(taskLine), "No follow-up tasks proposed."),
    section("Unresolved research gaps", gaps.map(taskLine), "No open research tasks."),
  ];

  return `# Research Report

_Generated by \`kos research\` on ${input.now}. **Research is evidence, not truth.**
These documents gather and cite external evidence under \`07 Research/\`; they are
not canonical knowledge and are never promoted automatically. This report derives
its state from task status — there is no separate event log._

Research tasks: ${research.length} (completed ${completed.length}, failed ${failed.length}, open ${gaps.length}).

${sections.join("\n\n")}
`;
}
