/**
 * Markdown renderer for the Semantic Report (`90 Meta/Semantic Report.md`).
 *
 * Pure function of a `SemanticReview`. The report is explicitly advisory: it
 * states up front that findings never block readiness and never become compiler
 * errors, and it labels low-confidence / suggestion findings as the ones that
 * are surfaced but not turned into work.
 */
import {
  type SemanticReview,
  type SemanticFinding,
  type SemanticFindingClass,
} from "../core/semantic-rules.js";

/** Display order + headings for the finding classes (strongest signal first). */
const CLASS_SECTIONS: { class: SemanticFindingClass; heading: string }[] = [
  { class: "possible_contradiction", heading: "Possible Contradictions" },
  { class: "recommendation", heading: "Recommendations" },
  { class: "observation", heading: "Observations" },
  { class: "suggestion", heading: "Suggestions" },
];

function citedDocs(documents: string[]): string {
  if (documents.length === 0) return "_(none cited)_";
  return documents.map((d) => `\`${d}\``).join(", ");
}

function renderFinding(f: SemanticFinding): string {
  const lowConf =
    f.confidence === "low" ? " — _low confidence; advisory only_" : "";
  return [
    `### ${f.title}  _(confidence: ${f.confidence}${lowConf})_`,
    `- **Why it matters:** ${f.reasoning}`,
    `- **Documents:** ${citedDocs(f.supportingDocuments)}`,
    `- **Recommended action:** ${f.recommendedAction}`,
  ].join("\n");
}

/** Render the full Semantic Report from a review. */
export function renderSemanticReport(review: SemanticReview, now: string): string {
  const sections = CLASS_SECTIONS.map(({ class: cls, heading }) => {
    const items = review.findings.filter((f) => f.class === cls);
    if (items.length === 0) return "";
    return `## ${heading}\n\n${items.map(renderFinding).join("\n\n")}`;
  }).filter((s) => s !== "");

  const body =
    review.findings.length === 0
      ? "_No semantic findings._"
      : sections.join("\n\n");

  const note = review.note !== undefined ? `\n_Reviewer note: ${review.note}_\n` : "";

  return `# Semantic Report

_Generated by \`kos analyze\` on ${now}. **Advisory only** — these findings review
reasoning, never block readiness, and never become compiler errors. Possible
contradictions become founder interviews; medium/high recommendations become
optional low-priority tasks; suggestions, observations, and low-confidence
findings are surfaced here but are **not** turned into work._
${note}
Findings: ${review.findings.length}.

${body}
`;
}
