/**
 * Task persistence.
 *
 * `90 Meta/tasks.json` is the machine source of truth. The human-readable
 * `Task Queue.md` / `Open Task Queue.md` are projections regenerated from it.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import {
  type KosTask,
  type TaskFile,
  TaskFileSchema,
  type TaskSpec,
  nextTaskId,
  taskKey,
} from "./task-model.js";
import { sortByPriority } from "../scheduler/scheduler.js";

function tasksFilePath(vaultPath: string): string {
  return path.join(vaultPath, "90 Meta", "tasks.json");
}

export function isoNow(clock?: () => Date): string {
  return (clock ? clock() : new Date()).toISOString();
}

/** Load tasks; returns [] when the file is absent. Throws on corrupt JSON. */
export async function loadTasks(vaultPath: string): Promise<KosTask[]> {
  const file = tasksFilePath(vaultPath);
  let raw: string;
  try {
    raw = await fs.readFile(file, "utf8");
  } catch (err) {
    // Missing task file is a normal "no tasks yet" state; rethrow anything else.
    if (
      typeof err === "object" &&
      err !== null &&
      (err as { code?: unknown }).code === "ENOENT"
    ) {
      return [];
    }
    throw err;
  }
  const parsed: TaskFile = TaskFileSchema.parse(JSON.parse(raw));
  return parsed.tasks;
}

export async function saveTasks(
  vaultPath: string,
  tasks: KosTask[],
): Promise<void> {
  const file = tasksFilePath(vaultPath);
  await fs.mkdir(path.dirname(file), { recursive: true });
  const payload: TaskFile = { version: 1, tasks };
  await fs.writeFile(file, JSON.stringify(payload, null, 2) + "\n", "utf8");
}

/**
 * Merge incoming task specs into existing tasks.
 *  - Existing tasks are kept (including their status).
 *  - An incoming spec matching an existing task by (type+goal) is dropped —
 *    we never resurrect or duplicate, and never revive a `complete` one.
 *  - Genuinely new specs are appended with fresh ids and timestamps.
 */
export function mergeTasks(
  existing: KosTask[],
  incoming: (TaskSpec | KosTask)[],
  now: string,
): KosTask[] {
  const seen = new Set(existing.map(taskKey));
  const result = [...existing];
  for (const spec of incoming) {
    const key = taskKey(spec);
    if (seen.has(key)) continue;
    seen.add(key);
    result.push({
      ...spec,
      id: nextTaskId(result),
      createdAt: now,
      updatedAt: now,
    });
  }
  return result;
}

/** Update one task in place (by id) returning a new array. */
export function updateTask(
  tasks: KosTask[],
  id: string,
  patch: Partial<KosTask>,
  now: string,
): KosTask[] {
  return tasks.map((t) =>
    t.id === id ? { ...t, ...patch, updatedAt: now } : t,
  );
}

// --- Markdown projections ---

function taskRow(t: KosTask): string {
  return `| ${t.id} | ${t.type} | ${t.priority} | ${t.status} | ${t.goal} |`;
}

const TABLE_HEADER =
  "| ID | Type | Priority | Status | Goal |\n| --- | --- | --- | --- | --- |";

/** Render the full task queue markdown (all tasks). */
export function renderTaskQueue(tasks: KosTask[], now: string): string {
  const sorted = sortByPriority(tasks);
  const rows = sorted.map(taskRow).join("\n") || "| — | — | — | — | _no tasks_ |";
  return `# Task Queue

_Generated by \`kos\` on ${now}. This is a projection of \`90 Meta/tasks.json\`; edit tasks through the CLI, not here._

${TABLE_HEADER}
${rows}

Total tasks: ${tasks.length}
`;
}

/** Render the open/in-progress queue. */
export function renderOpenTaskQueue(tasks: KosTask[], now: string): string {
  const open = sortByPriority(
    tasks.filter((t) => t.status === "open" || t.status === "in_progress"),
  );
  const rows = open.map(taskRow).join("\n") || "| — | — | — | — | _no open tasks_ |";
  return `# Open Task Queue

_Generated by \`kos\` on ${now}. Open and in-progress tasks, highest priority first._

${TABLE_HEADER}
${rows}

Open/in-progress: ${open.length} of ${tasks.length} total
`;
}
